title: GraphQL MCP Bridge
description: A TypeScript library for bridging GraphQL schemas with Model Context Protocol servers
theme: just-the-docs

url: https://pshaddel.github.io/graphql-mcp-bridge

# Use README.md as the homepage
readme_index: true

# Enable table of contents and heading anchors
heading_anchors: true

# Just the Docs theme configuration
# Enable search
search_enabled: true

# Enable copy code button
enable_copy_code_button: true

# Navigation footer
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/pshaddel/graphql-mcp-bridge"
gh_edit_branch: "main"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2025. Distributed by an <a href=\"https://github.com/pshaddel/graphql-mcp-bridge/tree/main/LICENSE\">MIT license.</a>"

# External links
aux_links:
  GitHub Repository: https://github.com/pshaddel/graphql-mcp-bridge